# Generated by Django 5.0.9 on 2026-07-15 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_achat', models.DateField()),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('statut_livraison', models.CharField(choices=[('ATTENTE', 'En attente'), ('PARTIELLE', 'Partielle'), ('RECUE', 'Reçue'), ('ANNULEE', 'Annulée')], default='ATTENTE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('total_ht_cache', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tva_cache', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc_cache', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='tiers.fournisseur')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date_achat', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_achetee', models.PositiveIntegerField()),
                ('prix_achat_unitaire_applique', models.DecimalField(decimal_places=2, max_digits=14)),
                ('taux_tva_applique', models.DecimalField(decimal_places=2, max_digits=4)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.achat')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_achat', to='produits.produit')),
            ],
            options={
                'verbose_name': "Ligne d'achat",
                'verbose_name_plural': "Lignes d'achat",
            },
        ),
    ]
