# Generated by Django 5.0.9 on 2026-07-15 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_vente', models.DateField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='VALIDEE', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('total_ht_cache', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tva_cache', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc_cache', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='tiers.client')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_realisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vendue', models.PositiveIntegerField()),
                ('prix_vente_unitaire_applique', models.DecimalField(decimal_places=2, max_digits=14)),
                ('taux_tva_applique', models.DecimalField(decimal_places=2, max_digits=4)),
                ('remise_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='produits.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
            },
        ),
    ]
