# Generated by Django 5.0.9 on 2026-07-15 21:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('type_facture', models.CharField(choices=[('ACHAT', 'Achat'), ('VENTE', 'Vente')], max_length=10)),
                ('date_facturation', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('achat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='achats.achat')),
                ('vente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_facturation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(default=django.utils.timezone.localdate)),
                ('montant_verse', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('CARTE', 'Carte'), ('VIREMENT', 'Virement'), ('MOBILE', 'Mobile Money')], default='ESPECES', max_length=10)),
                ('numero_transaction', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='facturation.facture')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglements_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Règlement',
                'verbose_name_plural': 'Règlements',
                'ordering': ['-date_paiement', '-id'],
            },
        ),
    ]
